import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ConvexClientProvider } from "./ConvexClientProvider";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";


/*const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});*/

export const metadata: Metadata = {
  title: "Chat_Cart",
  description: "Generated by create next app",
};

//const tabs = ["Home", "Products", "About"];
/*const tabs = [
  { label: "Home", href: "/" },
  { label: "Products", href: "/products" },
  { label: "About", href: "/about" },
];*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative w-full flex items-center justify-center" >
          
        </div>
        
        <ConvexClientProvider>
          <Navbar />
            {children}
          <Footer /> 
        </ConvexClientProvider>
        
      </body>
    </html>
  );
}
